spring.application.name=PractoSearch
spring.datasource.url=jdbc:mysql://localhost:3306/practoSearchDB?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Supragya@22
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=6e62d68e8f814f169b7c4cd1dbdc7a7b3d6db49e212d18bbfbc69c8039b2b86f
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
